### ISSUE TITLE
Rebuilding app fails when including discourse-saml

### ISSUE THREAD

**Issue by patrickhanft** [discourse/discourse-saml#4]
Hi there,

I tried to setup discourse with discourse-saml plugin, by following instructions in https://meta.discourse.org/t/install-a-plugin/19157 to include this github repository in the plugins section like this:

`containers/app.yml`:
```yaml
## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/discourse/discourse-saml.git
```

Unfortuntaly, the rebuild of the app fails with this:
```
[2016-07-16T10:51:14.096841 #15]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
NoMethodError: undefined method `saml_target_url' for GlobalSetting:Class
```

So, okay, I might need to add `saml_target_url` to the `discourse.conf` file, but actually I don't know, how to acchieve this in the docker environment.

I also tried to use the configuration options suggested by @BrianAdams in his pull request #3, but this seems to be not enough, I still get the error mentioned above.

Any clarification is very much appreciated!
